Make mailtemplates more modular
fabianlipp/useradmin pull request #18
Opened 2018-11-01 16:45 UTC by tmaex

2018-11-01 21:46 UTC, fabianlipp requested changes
Formatting: use spaces instead of tabs

2018-11-01 21:46 UTC, fabianlipp commented on addUser.php
> +		  'subject' => $template['subject'],
$mailSettings['subject'] (below) should not be needed anymore (and MAIL_SUBJECT is not defined anymore)

2018-11-01 21:46 UTC, fabianlipp commented on config.inc.php.template
> +  'addUser' = array(
Do we really need to distinguish two types of templates or should we always offer all templates (the variables in the template are the same)

2018-11-01 21:46 UTC, fabianlipp commented on config.inc.php.template
> +	)
Reinsert second example for template

2018-11-03 14:35 UTC, fabianlipp commented on addUser.php
> +		  'subject' => $template['subject'],
Not handled yet

2018-11-03 17:07 UTC, fabianlipp requested changes

2018-11-03 17:07 UTC, fabianlipp commented on config.inc.php.template
> -define('MAIL_SUBJECT', 'Your account for example.com');
Line 204 in addUser.php still references MAIL_SUBJECT (I think that line can be deleted)

2018-11-04 13:08 UTC, closed without merging

2018-11-04 13:21 UTC, tmaex commented on config.inc.php.template
> +  'addUser' = array(
The variables are the same right now, but they don't have to be in the future. Since this is would be a breaking change in another commit I'd rather seperate the templates yet.
Furthermore the list could get really long and I would save the few space you get in a modal body.